### PR TITLE
Adds a `selectDevice` method.

### PR DESCRIPTION
**Pull request by bicknellr**
You can use this method to directly select a specific device from `devices`. Throws if the device is not in the current list.

### CODE REVIEW

**Comment by bicknellr** [comment]
Does this count as fixing #18?

**Comment by bicknellr** [comment]
Also, I'm having trouble running tests - I'll have to get your input tomorrow.

**Comment by cdata** [comment]
> Does this count as fixing #18?

No, #18 would be satisfied by an easy, declarative way to say, "give me the front-facing camera." I think the best thing to solve this is some way to describe the constraints in a more straight-forward fashion.

**Comment by cdata** [comment]
Tests pass for me. LGTM 👍

**Pull request merged**
